### ISSUE TITLE
naming regression (i.e. zkevm vs. cdk) in test/docker-compose.yml

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygon/cdk-validium-node#46]
in the [file](https://github.com/0xPolygon/cdk-validium-node/blob/develop/test/docker-compose.yml), `cdk-validium` was changed back to `zkevm` in a few places

I noticed this b/c the docker images was changed as well. so I need to use command `/app/zkevm-node run` instead of `/app/cdk-validium-node run`

is this an intended change or a regression?

**Comment by gr8h** [comment]
does it work for you after you made this change?

**Comment by arnaubennassar** [comment]
Yes, this is intended in order to reduce the code diff vs `zkevm-node`
