### ISSUE TITLE
Errors when running cdk validium node

### ISSUE THREAD

**Issue by sondotpin** [0xPolygon/cdk-validium-node#78]
I've got that errors when running cdk validium node

`WARNING: Published ports are discarded when using host network mode`

`docker run -v "/tmp/cdk/test.prover.config.json:/usr/src/app/config.json" -p 50061:50061 -p 50071:50071 --network host hermeznetwork/zkevm-prover:v3.0.2 zkProver -c /usr/src/app/config.json`

https://docs.polygon.technology/cdk/get-started/deploy-validium/node/run-node-services

<img width="790" alt="Screen Shot 2024-02-16 at 15 09 12" src="https://github.com/0xPolygon/cdk-validium-node/assets/49492179/c5903b3d-bedd-4ac3-b4ad-4031fcceb672">

**Comment by kmurphypolygon** [comment]
Hi @sondotpin this is just a warning, you should be able to continue the flow.

**Comment by sondotpin** [comment]
```
root@ip-172-31-38-140:~# docker run -v "/tmp/cdk/test.prover.config.json:/usr/src/app/config.json" -p 50061:50061 -p 50071:50071 --network host hermeznetwork/zkevm-prover:v3.0.2 zkProver -c /usr/src/app/config.json

WARNING: Published ports are discarded when using host network mode

root@ip-172-31-38-140:~# docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                       PORTS                                       NAMES
4279da5b878d   hermeznetwork/zkevm-prover:v3.0.2   "zkProver -c /usr/sr…"   4 seconds ago   Exited (132) 4 seconds ago                                               condescending_lewin
2e50d879eede   postgres:15                         "docker-entrypoint.s…"   9 hours ago     Up 9 hours                   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   optimistic_bell
ce8eea66783c   postgres:15                         "docker-entrypoint.s…"   9 hours ago     Created                                                                  youthful_euclid
root@ip-172-31-38-140:~# docker logs -t 4279da5b878d
root@ip-172-31-38-140:~# docker exec -it /bin/bash 4279da5b878d
Error response from daemon: No such container: bin/bash
root@ip-172-31-38-140:~# docker exec 4279da5b878d -it /bin/bash
Error response from daemon: Container 4279da5b878d6fd881a75bf315c83615938b8d08646c91b34dbca02049ff797c is not running
root@ip-172-31-38-140:~#
```

The container not running @kmurphypolygon

**Comment by kmurphypolygon** [comment]
OK, @sondotpin I'm going to check on my side. Back soon.

**Comment by kmurphypolygon** [comment]
Just one quick question @sondotpin before I do a run myself. Did you make sure you removed all containers and images before trying again?

**Comment by kmurphypolygon** [comment]
Hi @sondotpin did you manage to solve your issue? We just made some changes to the instructions so I would recommend following along again and if you encounter the same, or another, problem, please do let us know asap.

**Comment by sondotpin** [comment]
sure. the reason is Core Intel. AMD is good. Thanks
