### ISSUE TITLE
Balance 0

### ISSUE THREAD

**Issue by sondotpin** [0xPolygon/cdk-validium-node#84]
The deployer's balance is 0 even though I followed the instructions correctly (L2 balance)

https://docs.polygon.technology/cdk/get-started/quickstart-validium/#4-add-the-network-to-a-web3-wallet.

In this tutorial balance should be 100000 POL

**Comment by kmurphypolygon** [comment]
Hi there @sondotpin I had this issue too. Did you check the troubleshooting box at the end of the section? I had to reset the nonce in MetaMask because I had restarted the application.

https://docs.polygon.technology/cdk/get-started/quickstart-validium/#4-add-the-network-to-a-web3-wallet

**Comment by sondotpin** [comment]
not yet.
```
curl -X POST localhost:8123 -H "Content-Type: application/json" --data '
{
  "jsonrpc": "2.0",
  "method": "eth_getBalance",
  "params": ["0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266", "latest"],
  "id": 1
}
'
```

Result 0

**Comment by kmurphypolygon** [comment]
@praetoriansentry for info ^^

**Comment by sondotpin** [comment]
solved. need to change in contract deploy. genesis.json

**Comment by kmurphypolygon** [comment]
Hi @sondotpin can you explain exactly what you did please?

**Comment by sondotpin** [comment]
https://github.com/0xPolygon/cdk-validium-contracts/blob/c6743885226690788b3474fa216622023f48bd98/deployment/1_createGenesis.js#L297

change this line before deploy contract to L1

**Comment by kmurphypolygon** [comment]
mmm, an interesting hack, thank you :) 
will tell the team
fyi @praetoriansentry

**Comment by praetoriansentry** [comment]
Generally, if you want to have value on L2 without bridging, you would run the deployment with the `--test` flag. Rather than changing the line that @sondotpin mentioned - you can also run the genesis creation script with `--test`
https://github.com/0xPolygon/cdk-validium-contracts/blob/c6743885226690788b3474fa216622023f48bd98/deployment/1_createGenesis.js#L302-L305

**Comment by kmurphypolygon** [comment]
Actually @praetoriansentry this is in relation to this step: https://docs.polygon.technology/cdk/get-started/quickstart-validium/#4-add-the-network-to-a-web3-wallet where there should be an account with value available.

On the first start, and until you restart, the value is available. If you restart without refreshing the nonce in MM, you get 0 value.

I think your answer is in relation to the deployment guide: https://docs.polygon.technology/cdk/get-started/deploy-validium/intro/ but we do not have send transaction documentation in here yet. Coming soon.
